name: GitHub-Profile-3D-Contrib

on:
  schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: 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{{ secrets.TOKEN }}
          USERNAME: snowriceDD{{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config snowriceDD github-actions
          git config yoons100457@gmail.com github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
